GET http://localhost:5000/employees

###
GET http://localhost:5000/employees/2

###
POST http://localhost:5000/employees
Content-Type: application/json

{
  "first_name": "Rafi",
  "last_name": "Kadafi",
  "department": "Buseniss Management",
  "gender": "Male",
  "age": 18,
  "salary": 5500000
}

###
PUT http://localhost:5000/employees/2
Content-Type: application/json

{
  "first_name": "Michael",
  "last_name": "Salamanca",
  "department": "IT - FullStack",
  "gender": "Female",
  "age": 18,
  "salary": 8000000
}

###
DELETE  http://localhost:5000/employees/4
